apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aci-hellorazor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aci-hellorazor
    spec:
      containers:
      - name: aci-hellorazor
        image: spboyer/hellorazor
        ports:
        - containerPort: 80
      nodeName: aci-connector